use_frameworks!

platform :ios, '10.0'

target 'MKGatewayThree_Example' do
  pod 'MKGatewayThree', :path => '../'

  target 'MKGatewayThree_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
